[package]
name = "streaming"
version = "0.1.0"
edition = "2021"

[dependencies]
cryptr = { path = "../..", features = ["streaming"] }

anyhow = "1.0.75"
sha2 = "0.10.8"
tokio = { version = "1.35.0", features = ["rt-multi-thread"] }
